apiVersion: v1
kind: ConfigMap
metadata:
  name: gfc-config
  namespace: gfc
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  PROMETHEUS_PORT: "9090"
  P2P_PORT: "6000"
  MAX_PEERS: "50"

---
apiVersion: v1
kind: Secret
metadata:
  name: gfc-secrets
  namespace: gfc
type: Opaque
data:
  JWT_SECRET: base64_encoded_jwt_secret
  DB_PASSWORD: base64_encoded_db_password
  BIOMETRIC_API_KEY: base64_encoded_api_key

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gfc-data-pvc
  namespace: gfc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard 