apiVersion: v1
kind: Secret
metadata:
  name: gfc-secrets
  namespace: gfc
type: Opaque
data:
  DB_PASSWORD: base64_encoded_password
  RABBITMQ_USER: base64_encoded_user
  RABBITMQ_PASSWORD: base64_encoded_password
  JWT_SECRET: base64_encoded_secret
  API_KEYS: base64_encoded_keys 