global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gfc-services'
    static_configs:
      - targets: ['identity-service:8080', 'transaction-service:8080', 'consensus-service:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 